## Batch Gradient Decent 

Partial Derivative of the code function

MSE(0) = 2/m sum(0T.x^(i)-y^(i))xj^(i)

Gradient Decent Next Step 

0^(next step) = 0-n*MSSE(0)

In [23]:
import numpy as np 

X = 2*np.random.rand(100,1)
y = 4 + 3 * X + np.random.rand(100,1)

X_b = np.c_[np.ones((100,1)),X]  # add x0 = 1 to each instance

theta_best = np.linalg.inv(X_b.T.dot(X_b)).dot(X_b.T).dot(y)

theta_best

array([[4.50348339],
       [2.97048065]])

In [24]:
eta  = 0.1
n = 1000
m = 100

theta  = np.random.randn(2,1)

for i in range(n):
    gradients = 2/m * X_b.T.dot(X_b.dot(theta)-y)
    theta = theta - eta * gradients

theta

array([[4.50348339],
       [2.97048065]])

## Stochatic Gradient Decent 

In [44]:
n_epochs = 50
t0 , t1 = 5,50

def learning_schedule(t):
    return t0 / (t + t1)


for epoch in range(n_epochs):
    for i in range(m):
        random_index = np.random.randint(m)
        xi = X_b[random_index:random_index+1]
        yi = y[random_index:random_index+1]
        gradients = 2 * xi.T.dot(xi.dot(theta) - yi)
        eta = learning_schedule(epoch * m + i)
        theta = theta - eta * gradients

theta

array([[4.50452093],
       [2.97603759]])

In [26]:
from sklearn.linear_model import SGDRegressor

sgd_reg = SGDRegressor(max_iter=1000,tol=1e-3,penalty= None,eta0=0.1)

sgd_reg.fit(X,y.ravel())
sgd_reg.intercept_,sgd_reg.coef_

(array([4.4979238]), array([3.00324141]))