## Numpy Array Operations

In [2]:
import numpy as np

## Sclicing

In [10]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

print("Basic Sclicing:: ", arr[3:4])
print("With Step Sclicing:: ", arr[1:10:2])
print("Negitive Indexing Sclicing:: ", arr[3:-4])

Basic Sclicing::  [4]
With Step Sclicing::  [ 2  4  6  8 10]
Negitive Indexing Sclicing::  [4 5 6]


In [24]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("Specific Element:: ",arr_2d[0,1])
print("Entire Row:: ",arr_2d[2])
print("Entire Column:: ",arr_2d[:, 1])


Specific Element::  2
Entire Row::  [7 8 9]
Entire Column::  [2 5 8]


## Sorting

In [ ]:
unsorted = np.array([6,4,8,5,9,2,1,3,7])

print("Sorted Array:: ", np.sort(unsorted))

unsorted_2d = np.array([[6,4,8,5],[9,2,3,7]])
print("Sorted 2d Array Column Wise:: ",np.sort(unsorted_2d,axis = 0))
print("Sorted 2d Array Row Wise:: ",np.sort(unsorted_2d,axis = 1))


Sorted Array::  [1 2 3 4 5 6 7 8 9]
Sorted 2d Array::  [[6 2 3 5]
 [9 4 8 7]]
Sorted 2d Array::  [[4 5 6 8]
 [2 3 7 9]]


## Filtering Array

In [27]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
print("Even Numbers:: ", numbers[numbers % 2 == 0])

Even Numbers::  [ 2  4  6  8 10]


## Filtering Array by Masks 


In [28]:
mask = numbers > 5
print("Numbers Grater than 5:: ",numbers[mask])

Numbers Grater than 5::  [ 6  7  8  9 10]


## Fancy Indexing vs np.where()

In [29]:
indices = [0,2,4]
print("Fancy Indexing:: ", numbers[indices])

Fancy Indexing::  [1 3 5]


In [30]:
where_result  = np.where(numbers > 5)
print("Numbers Using Where:: ",numbers[where_result])

Numbers Using Where::  [ 6  7  8  9 10]


In [33]:
condition_array = np.where(numbers > 5,numbers*2 , numbers)
print("Conditionsal Array:: ", condition_array)

Conditionsal Array::  [ 1  2  3  4  5 12 14 16 18 20]


## Add and Removing Data 

In [38]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
combined = np.concatenate((arr1,arr2))
print("Concatinated:: " , combined)

Concatinated::  [1 2 3 4 5 6]


## Array Compatibility

In [40]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr3 = np.array([7,8,9])

print("Compatibility:: ", arr1.shape == arr2.shape)

Compatibility::  True


In [47]:
oringinal  = np.array([[1,2,3],[4,5,6]])
to_add = np.array([7,8,9])

add_row = np.vstack((oringinal,to_add))
print("Added Row:: ", add_row)

to_add_col  = np.array([[7],[8]])

add_col = np.hstack((oringinal,to_add_col))
print("Added Col:: ",add_col)

Added Row::  [[1 2 3]
 [4 5 6]
 [7 8 9]]
Added Col::  [[1 2 3 7]
 [4 5 6 8]]


In [53]:
arr  = np.array([[1,2,3,4,5,6]])
deleted = np.delete(arr,[4])
print(deleted)

[1 2 3 4 6]
